# Generated by Django 5.1 on 2024-08-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('student_class', models.TextField(max_length=20)),
                ('fathername', models.TextField()),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
