# Generated by Django 5.1 on 2024-08-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curd_app', '0002_alter_student_fathername_alter_student_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
